baseURL = "https://unitn-spot.github.io"

title = "Students of Photonics - unitn"
author = "StuPhos"
copyright = "Copyright © 2025, StuPhos."
languageCode = "en-US"

theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["activities"]

[params]
hideFooter = true
disableSpecial1stPost = true

[params.cover]
responsiveImages = false
linkFullImages = false

[params.label]
text = " "
icon = "images/logo.png"
iconHeight = 35

[params.assets]
# favicon = "" When we will have a "round" logo place it here!
theme_color = "#000000"
disableHLJS = true

[params.editPost]
text = ""

# disableAnchoredHeadings = true
[params.homeInfoParams]
AlignSocialIconsTo = "left"

[[params.socialIcons]]
name = "instagram"
title = "Instagram Page"
url = "https://www.instagram.com/spieunitn/"

[[params.socialIcons]]
name = "youtube"
title = "Youtube Channel"
url = "https://www.youtube.com/@trentospiestudentchapter5644/"

[[params.socialIcons]]
name = "facebook"
title = "Facebook Page"
url = "https://www.facebook.com/profile.php?id=100083412673552"
